Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
      v.memory = 512
    end

    # config.vm.network "forwarded_port", id: "ssh", host: 54321, guest: 54321

    config.vm.define "dbserver" do |db|
      db.vm.box = "ubuntu/xenial64"
      # db.vm.box = "generic/ubuntu2004"
      db.vm.hostname = "dbserver"
      db.vm.network :private_network, ip: "10.10.10.10"
      # db.vm.network :private_network, type: "dhcp"

      db.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
        "db" => ["dbserver"],
        "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
        }
      end
    end

    config.vm.define "appserver" do |app|
      app.vm.box = "ubuntu/xenial64"
      # app.vm.box = "generic/ubuntu2004"
      app.vm.hostname = "appserver"
      app.vm.network :private_network, ip: "10.10.10.20"
      # app.vm.network :private_network, type: "dhcp"

      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
        "app" => ["appserver"],
        "app:vars" => {"db_host" => "10.10.10.10"}
        }
        ansible.extra_vars = {
          "deploy_user" => "vagrant",
          "nginx_sites"=> {
            "default" => [
              "listen 80",
              "server_name \"reddit-app\"",
              "location / {
                proxy_pass http://127.0.0.1:9292;
              }"
            ]
          }
        }
      end
    end
  end
